# 100 numpy exercises with hint

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
np.__version__

'1.16.2'

In [3]:
np.show_config

<function numpy.__config__.show()>

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [4]:
vector =np.zeros(10)

vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [11]:
vector.size

10

In [13]:
vector.itemsize

8

In [15]:
print("%d bytes" % (vector.size*vector.itemsize))

80 bytes


In [17]:
#pyformat.info

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [20]:
np.info()

 info(object=None, maxwidth=76,
      output=<ipykernel.iostream.OutStream object at 0x0000020059B61CF8>,
      toplevel='numpy')

Get help information for a function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is a
    numpy object, its docstring is given. If it is a string, available
    modules are searched for matching objects.  If None, information
    about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``stdout``.  The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

See Also
--------
source, lookfor

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> np.info(np.polyval) # doctest: +

In [ ]:
#shift + tab

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [21]:
z = np.zeros(10)

In [22]:
z[4]= 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [24]:
z= np.arange(10,50)
z

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [28]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity= "all"

In [26]:
print(z[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [29]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [30]:
first_list = [1,2,0,0,4,0]
print(repr(np.nonzero(first_list)))

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [31]:
np.identity(n=5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [53]:
np.random.random((3,3,3))

array([[[0.43282874, 0.10898814, 0.66291452],
        [0.83081278, 0.85986261, 0.42253106],
        [0.32234541, 0.13312229, 0.07628816]],

       [[0.51546652, 0.09414606, 0.38429463],
        [0.02666302, 0.77375623, 0.42233948],
        [0.38891064, 0.14203988, 0.96987797]],

       [[0.86348054, 0.62962384, 0.90701572],
        [0.82583259, 0.9625013 , 0.96450988],
        [0.76069866, 0.92259641, 0.56294671]]])

In [54]:
np.random.random(27).reshape((3,3,3))

array([[[0.43723646, 0.38701403, 0.46911585],
        [0.69415487, 0.59530141, 0.23325146],
        [0.70986685, 0.10655103, 0.46555829]],

       [[0.72824359, 0.43937925, 0.32711461],
        [0.4687038 , 0.4554203 , 0.46675875],
        [0.72047518, 0.27938405, 0.97947651]],

       [[0.61530943, 0.751949  , 0.18396051],
        [0.87974353, 0.59725761, 0.19718841],
        [0.52244408, 0.02939982, 0.49058383]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [50]:
array_1010 = np.random.random((10,10))

In [51]:
print(array_1010)

[[0.76019422 0.44649444 0.11870362 0.15155928 0.0273234  0.71164772
  0.70523487 0.86068459 0.38280937 0.91238934]
 [0.6864232  0.21729817 0.91498887 0.13308021 0.831661   0.09859214
  0.01627644 0.62445805 0.81776673 0.27712694]
 [0.78372175 0.51804956 0.27951883 0.34827204 0.20747213 0.31986941
  0.74257077 0.45454035 0.18966845 0.67833634]
 [0.39254411 0.59291874 0.54065597 0.81461849 0.81652351 0.00697652
  0.19670553 0.58113815 0.90806985 0.34690154]
 [0.41024933 0.84796951 0.43331714 0.75881483 0.64286213 0.55097323
  0.45152638 0.72105708 0.74333716 0.35886878]
 [0.59765836 0.87249799 0.00364134 0.86811475 0.88059857 0.48711935
  0.41573957 0.850402   0.75970834 0.86087502]
 [0.50961295 0.17198209 0.91809109 0.71041938 0.74638599 0.395174
  0.17514857 0.09044923 0.47558495 0.36925682]
 [0.8706247  0.07017435 0.16593279 0.09849512 0.03173257 0.48104143
  0.44499413 0.04179329 0.95433127 0.25110094]
 [0.26369171 0.34560162 0.9407954  0.22670438 0.28130135 0.31672382
  0.34178609 0

In [38]:
array_1010.min()

0.0003052271373080728

In [39]:
array_1010.max()

0.9932166054628278

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [55]:
random_vector = np.random.random(30)

In [56]:
random_vector

array([0.17917405, 0.4533427 , 0.18708592, 0.53454368, 0.66163585,
       0.84598418, 0.58695904, 0.06535034, 0.55197013, 0.69716698,
       0.92534574, 0.54061588, 0.52053345, 0.55595846, 0.99135096,
       0.53925159, 0.66843658, 0.47683112, 0.42684847, 0.52380421,
       0.44502122, 0.34886323, 0.29084885, 0.06185153, 0.86531472,
       0.70735336, 0.65618859, 0.93937659, 0.02206744, 0.12633162])

In [58]:
random_vector.mean()

0.5131802156724858

In [59]:
np.random.random(30).mean()

0.4859675815798401

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [65]:
#np.zeros((10,10))
#np.one((10,10))

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [64]:
initial_array= np.ones((10,10))
array_padded =np.pad(initial_array, pad_width=1, mode='constant', constant_values=0)

print(repr(array_padded))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [66]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

nan

False

False

nan

True

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [76]:
x =np.arange(1,5)
 
np.diag(x, k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [78]:
initial_array = np.zeros((8,8))
initial_array[1::2, ::2]=1
initial_array[::2,1::2]=1

print(repr(initial_array))

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [79]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

In [81]:
np.random.random((6,7,8))

array([[[0.73134005, 0.13769509, 0.67231564, 0.39204439, 0.88885781,
         0.53526934, 0.18825222, 0.72651205],
        [0.26233453, 0.53678548, 0.59605624, 0.42047905, 0.44751118,
         0.03120842, 0.84700434, 0.34208748],
        [0.62182305, 0.73154756, 0.56412585, 0.47109005, 0.63042323,
         0.75824049, 0.70844188, 0.6003158 ],
        [0.13174634, 0.97068112, 0.95374388, 0.0658232 , 0.94126576,
         0.24541182, 0.55642062, 0.5683341 ],
        [0.50149529, 0.52550542, 0.22684784, 0.34747785, 0.16031927,
         0.84782796, 0.54093896, 0.6031927 ],
        [0.33126156, 0.43104095, 0.94300311, 0.52895649, 0.76968677,
         0.52040731, 0.3042754 , 0.80037632],
        [0.54616072, 0.51605223, 0.90802427, 0.45742601, 0.75094635,
         0.98211634, 0.66801181, 0.64287414]],

       [[0.86309764, 0.63159213, 0.45446352, 0.61776848, 0.80405677,
         0.29930435, 0.48170031, 0.69418206],
        [0.00227521, 0.59046937, 0.30009292, 0.23912332, 0.90035302,
         

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [5]:
import numpy as np

In [6]:
np.tile(np.array([[0,1], [1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - mean) / std)

In [10]:
nnm= np.random.random((5,5))

normal_matrix = (nnm - np.mean(nnm)) / (np.std(nnm))
normal_matrix

array([[ 0.18118617, -0.30850115,  0.04029385, -0.64783626,  1.26102445],
       [-1.34377858, -1.44784342, -1.48002027, -0.4381568 ,  1.07948113],
       [ 0.74116443, -0.14309536, -0.26793289,  0.34404113,  1.43373291],
       [ 2.08643035, -0.64717651,  0.05333889,  0.93203694,  1.3551676 ],
       [-1.19203706, -1.29811989, -1.12702697, -0.02560809,  0.85923539]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [7]:
color = \
np.dtype(
[
    ('r', np.ubyte, 1),
    ('g', np.ubyte, 1),
    ('b', np.ubyte, 1),
    ('a', np.ubyte, 1)
]
)
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [21]:
np.dot(np.random.random((5,3)),np.random.random((3,2)))

array([[0.47751891, 1.10504521],
       [0.48508322, 1.16136537],
       [0.25113031, 0.55766394],
       [0.57948202, 1.12993798],
       [0.77391581, 1.64937165]])

In [ ]:
np.ones((5,3))@np.ones((3,2))

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [23]:
initial_array = np.arange(15)

In [25]:
initial_array[
    (initial_array>3)&
    (initial_array<=8)
]\
*=-1
print(initial_array)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10 11 12 13 14]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [31]:
list(zip(range(5)))

[(0,), (1,), (2,), (3,), (4,)]

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [42]:
Z= np.arange(5)

In [43]:
Z**Z

array([  1,   1,   4,  27, 256], dtype=int32)

In [44]:
2 << Z >> 2

array([0, 1, 2, 4, 8], dtype=int32)

In [45]:
Z <- Z

array([False, False, False, False, False])

In [46]:
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [47]:
Z/1/1

array([0., 1., 2., 3., 4.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [50]:
np.array(0) / np.array(0)

C:\Users\L03040500\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [51]:
np.array(0) // np.array(0)

C:\Users\L03040500\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [52]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [54]:
np.random.uniform(low=-10, high=10, size=10)

array([ 9.68660413,  0.34151925, -3.18077675,  6.83853541,  2.84511342,
        5.82038979, -1.15867324, -8.4108768 , -8.08563009, -0.21049292])

In [58]:
Z = np.random.uniform(low=-10, high=10, size=10)
np.copysign(np.ceil(np.abs(Z)),Z)

array([-1.,  6., -7., -3.,  6.,  5., -8., -6., -7., -3.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [57]:
array_one = np.array([1,2,3,4,5,6])

array_two = np.array([3,4,92,92,100,5])

np.intersect1d(array_one, array_two)

array([3, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [1]:
import numpy as np

In [3]:
defaults = np.seterr(all='ignore')

In [5]:
z = np.ones(1)/0

z

array([inf])

In [7]:
np.seterr(**defaults)

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [8]:
with np.errstate(divide='ignore'):
    Z= np.ones(1)/0
    print(repr(Z))

array([inf])


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [10]:
np.sqrt(-1)  #imaginary

nan

In [12]:
np.emath.sqrt(-1)  #complex plain
#by default , ai +- bj is supported, so negatives/imaginaries are supported

1j

In [13]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [22]:
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')

In [24]:
yesterday

numpy.datetime64('2019-09-10')

In [30]:
tomorrow = np.datetime64('today','W') + np.timedelta64(52,'W')

In [31]:
tomorrow

numpy.datetime64('2020-09-03')

In [33]:
many_years = np.datetime64('today','Y') + np.timedelta64(52,'Y')
many_years

numpy.datetime64('2071')

In [35]:
one_month = np.datetime64('today','M') + np.timedelta64(1,'M')
one_month

numpy.datetime64('2019-10')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [39]:
july_2016_dates = \
np.arange(
    '2019-09-11',
    '2019-10-11',
    dtype='datetime64[D]'
)

print(repr(july_2016_dates))

array(['2019-09-11', '2019-09-12', '2019-09-13', '2019-09-14',
       '2019-09-15', '2019-09-16', '2019-09-17', '2019-09-18',
       '2019-09-19', '2019-09-20', '2019-09-21', '2019-09-22',
       '2019-09-23', '2019-09-24', '2019-09-25', '2019-09-26',
       '2019-09-27', '2019-09-28', '2019-09-29', '2019-09-30',
       '2019-10-01', '2019-10-02', '2019-10-03', '2019-10-04',
       '2019-10-05', '2019-10-06', '2019-10-07', '2019-10-08',
       '2019-10-09', '2019-10-10'], dtype='datetime64[D]')


In [40]:
print(july_2016_dates)

['2019-09-11' '2019-09-12' '2019-09-13' '2019-09-14' '2019-09-15'
 '2019-09-16' '2019-09-17' '2019-09-18' '2019-09-19' '2019-09-20'
 '2019-09-21' '2019-09-22' '2019-09-23' '2019-09-24' '2019-09-25'
 '2019-09-26' '2019-09-27' '2019-09-28' '2019-09-29' '2019-09-30'
 '2019-10-01' '2019-10-02' '2019-10-03' '2019-10-04' '2019-10-05'
 '2019-10-06' '2019-10-07' '2019-10-08' '2019-10-09' '2019-10-10']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [52]:
#.copy prevent the other data from being updated
#inplace= True That marameter has been helpfull to be an anternative for copy()


A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3

In [53]:
np.add(A,B, out=B)

array([3., 3., 3.])

In [54]:
np.divide(A, 2, out=A)
A

array([0.5, 0.5, 0.5])

In [55]:
A

array([0.5, 0.5, 0.5])

In [56]:
np.negative(A, out=A)

array([-0.5, -0.5, -0.5])

In [57]:
A

array([-0.5, -0.5, -0.5])

In [58]:
np.multiply(A,B, out=A)

array([-1.5, -1.5, -1.5])

In [59]:
B

array([3., 3., 3.])

In [60]:
A

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [64]:
Z= np.random.uniform(0,10,10)

In [66]:
print(repr(Z))

array([1.08428864, 4.08610991, 0.03681892, 4.98591103, 6.95338367,
       8.15992641, 7.5320078 , 1.27230219, 2.6422655 , 4.63297065])


In [68]:
print(Z - Z % 1)

[1. 4. 0. 4. 6. 8. 7. 1. 2. 4.]


In [69]:
Z

array([1.08428864, 4.08610991, 0.03681892, 4.98591103, 6.95338367,
       8.15992641, 7.5320078 , 1.27230219, 2.6422655 , 4.63297065])

In [71]:
Z%1

array([0.08428864, 0.08610991, 0.03681892, 0.98591103, 0.95338367,
       0.15992641, 0.5320078 , 0.27230219, 0.6422655 , 0.63297065])

In [73]:
np.floor(Z)

array([1., 4., 0., 4., 6., 8., 7., 1., 2., 4.])

In [74]:
print(Z.astype(dtype=int))

[1 4 0 4 6 8 7 1 2 4]


In [75]:
print(np.trunc(Z))

[1. 4. 0. 4. 6. 8. 7. 1. 2. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [80]:
x = np.zeros((5,5))

In [82]:
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [83]:
x+=np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [84]:
def generate():
    for x in range(10):
        yield x

np.fromiter(generate(), dtype=float, count=-1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [86]:
np.linspace(0,1,11, endpoint = False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [92]:
Z= np.random.random(10)
Z.sort()
print(Z)

[0.07134032 0.29537015 0.50613087 0.55899542 0.58656446 0.70880865
 0.75077968 0.77428397 0.85437424 0.90287891]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [3]:
import numpy as np 

In [6]:
array = np.array([1,2,3,4,4])

In [8]:
np.add.reduce(array)

14

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [9]:
A = np.random.random(5)
B = np.random.random(5)

In [10]:
A

array([0.21965496, 0.10446173, 0.89105215, 0.1148289 , 0.89666119])

In [11]:
B

array([0.95532552, 0.934733  , 0.48604153, 0.15147753, 0.55010998])

In [13]:
np.array_equal(A,B)

False

In [14]:
np.allclose(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [17]:
array_example = np.array([(1,2,3),(4,5,6)])

In [20]:
array_example.flags.writeable = False

In [22]:
array_example.flags.writeable

False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [29]:
matrix = np.random.random(20).reshape(10,2)

In [55]:
x, y =matrix[0:,0], matrix[0:,1]

In [57]:
x

array([0.27162991, 0.41549884, 0.48553866, 0.72587417, 0.34735159,
       0.16262333, 0.07165657, 0.531929  , 0.36861135, 0.99187813])

In [58]:
y

array([0.42481182, 0.70819075, 0.76974539, 0.77362511, 0.84893931,
       0.07749146, 0.42598215, 0.8579084 , 0.64913247, 0.68432598])

In [60]:
r = np.sqrt(x**2+y**2)

In [61]:
r

array([0.50422999, 0.82108064, 0.91008557, 1.06084358, 0.91725192,
       0.18014237, 0.43196697, 1.00943315, 0.74648998, 1.20504119])

In [65]:
angle = np.arctan2(y,x)

In [66]:
angle

array([1.00190016, 1.04021015, 1.00805264, 0.817232  , 1.18241884,
       0.4446787 , 1.40414159, 1.01577888, 1.05435035, 0.60393522])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [104]:
vector = np.random.randint(1, size=10, high= 11)

In [105]:
vector

array([7, 1, 5, 1, 2, 1, 2, 1, 8, 6])

In [106]:
#returns the index of the maximum values
vector[np.argmax(vector)]=0

In [107]:
vector

array([7, 1, 5, 1, 2, 1, 2, 1, 0, 6])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [16]:
x = [1,0,0,0,0,0,0,0]
y = [1,0,0,0,0,0,0,0]


In [17]:
np.meshgrid(x,y)

[array([[1, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0]]), array([[1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]])]

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [18]:
np.multiply.outer([1, 2, 3], [4, 5, 6])

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [25]:
np.iinfo(np.int16)

iinfo(min=-32768, max=32767, dtype=int16)

In [31]:
np.iinfo(np.int32)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [42]:
array = np.array([1,2,3,4,5])

In [36]:
np.set_printoptions(array)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [38]:
a = np.arange(6).reshape(2,3)

In [40]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [45]:
np.argmin(a)

0

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [74]:
array = np.arange(200).reshape(100,2)

In [76]:
np.atleast_2d(array)

array([[  0,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9],
       [ 10,  11],
       [ 12,  13],
       [ 14,  15],
       [ 16,  17],
       [ 18,  19],
       [ 20,  21],
       [ 22,  23],
       [ 24,  25],
       [ 26,  27],
       [ 28,  29],
       [ 30,  31],
       [ 32,  33],
       [ 34,  35],
       [ 36,  37],
       [ 38,  39],
       [ 40,  41],
       [ 42,  43],
       [ 44,  45],
       [ 46,  47],
       [ 48,  49],
       [ 50,  51],
       [ 52,  53],
       [ 54,  55],
       [ 56,  57],
       [ 58,  59],
       [ 60,  61],
       [ 62,  63],
       [ 64,  65],
       [ 66,  67],
       [ 68,  69],
       [ 70,  71],
       [ 72,  73],
       [ 74,  75],
       [ 76,  77],
       [ 78,  79],
       [ 80,  81],
       [ 82,  83],
       [ 84,  85],
       [ 86,  87],
       [ 88,  89],
       [ 90,  91],
       [ 92,  93],
       [ 94,  95],
       [ 96,  97],
       [ 98,  99],
       [100, 101],
       [102, 103],
       [104,

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [51]:
float_array = np.array([1.0,2.0,3.0,4.0])

In [52]:
type(float_array)

numpy.ndarray

In [54]:
float_array.dtype

dtype('float64')

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
data = np.genfromtxt(file, delimiter=",")

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [79]:
a = np.array([1,2,3,4])

In [81]:
a

array([1, 2, 3, 4])

In [87]:
for i in np.ndenumerate(a):
    print(i)

((0,), 1)
((1,), 2)
((2,), 3)
((3,), 4)


In [89]:
for index in np.ndindex(3, 2):
    print(index)

(0, 0)
(0, 1)
(1, 0)
(1, 1)
(2, 0)
(2, 1)


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray | np.unique)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)